services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: pZWIkzG%#pvP0F7TslHPRQdZ1s&PuS
        ports:
            - 5432:5432
        networks:
            - postgres-network
        # 限制docker log檔案大小
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
    pgadmin4:
        container_name: pgadmin4
        image: dpage/pgadmin4
        restart: always
        ports:
            - 8080:80
        environment:
            PGADMIN_DEFAULT_EMAIL: p26763067@gmail.com
            PGADMIN_DEFAULT_PASSWORD: YR4GAn2NAjxwTmvc5I$Y8BBL@ldoNH
        networks:
            - postgres-network
        # 限制docker log檔案大小
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
networks:
    postgres-network:
        name: postgres-network
